services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - COHERE_API_KEY=${COHERE_API_KEY}
      - ENVIRONMENT=production  
      - MODEL_NAME=command-r-plus-04-2024
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_PORT=8000
    volumes:
      - ./src:/app/src
      - chroma_data:/app/chroma_db
    depends_on:
      init-db:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - rick_morty_net

  chromadb:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - ALLOW_RESET=True
      - ANONYMIZED_TELEMETRY=False
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rick_morty_net

  init-db:
    build: .
    volumes:
      - ./src:/app/src
      - chroma_data:/app/chroma_db
    command: python -m src.init_db
    environment:
      - COHERE_API_KEY=${COHERE_API_KEY}
      - ENVIRONMENT=production
      - MODEL_NAME=command-r7b-12-2024
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_PORT=8000
    depends_on:
      chromadb:
        condition: service_healthy
    networks:
      - rick_morty_net

#  frontend:
#    image: rick-morty-front:latest 
#    ports:
#      - "80:80"
#    depends_on:
#      - app
#    networks:
#      - rick_morty_net

networks:
  rick_morty_net:
    driver: bridge

volumes:
  chroma_data: